// This file is autogenerated at 'scripts/shooter_calcs/main.py'.
package robot.subsystems.shooter.math;

import robot.subsystems.shooter.DataTypes.ShotMapResult;

import static java.util.Map.entry;

public final class GroundShotMap extends ShotMap {
    public GroundShotMap() {
        put(
            0.50000,
            entry(1.67844, new ShotMapResult(0.78540, 0.43519)),
            entry(1.71295, new ShotMapResult(0.82903, 0.44637)),
            entry(1.75353, new ShotMapResult(0.87266, 0.45836)),
            entry(1.80098, new ShotMapResult(0.91630, 0.47131)),
            entry(1.85629, new ShotMapResult(0.95993, 0.48541)),
            entry(1.92075, new ShotMapResult(1.00356, 0.50091)),
            entry(1.99601, new ShotMapResult(1.04720, 0.51813)),
            entry(2.08428, new ShotMapResult(1.09083, 0.53748)),
            entry(2.18851, new ShotMapResult(1.13446, 0.55952)),
            entry(2.31280, new ShotMapResult(1.17810, 0.58502)),
            entry(2.46297, new ShotMapResult(1.22173, 0.61509)),
            entry(2.64768, new ShotMapResult(1.26536, 0.65137)),
            entry(2.88045, new ShotMapResult(1.30900, 0.69646)),
            entry(3.18381, new ShotMapResult(1.35263, 0.75468)),
            entry(3.59890, new ShotMapResult(1.39626, 0.83395)),
            entry(4.21081, new ShotMapResult(1.43990, 0.95065))
        );
        put(
            1.00000,
            entry(2.69146, new ShotMapResult(0.78540, 0.54611)),
            entry(2.72864, new ShotMapResult(0.82903, 0.56395)),
            entry(2.77528, new ShotMapResult(0.87266, 0.58294)),
            entry(2.83238, new ShotMapResult(0.91630, 0.60333)),
            entry(2.90125, new ShotMapResult(0.95993, 0.62539)),
            entry(2.98363, new ShotMapResult(1.00356, 0.64950)),
            entry(3.08181, new ShotMapResult(1.04720, 0.67611)),
            entry(3.19882, new ShotMapResult(1.09083, 0.70582)),
            entry(3.33883, new ShotMapResult(1.13446, 0.73946)),
            entry(3.50757, new ShotMapResult(1.17810, 0.77813)),
            entry(3.71333, new ShotMapResult(1.22173, 0.82343)),
            entry(3.96839, new ShotMapResult(1.26536, 0.87774)),
            entry(4.29196, new ShotMapResult(1.30900, 0.94470)),
            entry(4.71594, new ShotMapResult(1.35263, 1.03039)),
            entry(5.29750, new ShotMapResult(1.39626, 1.14554)),
            entry(6.14886, new ShotMapResult(1.43990, 1.31087))
        );
        put(
            1.50000,
            entry(3.47410, new ShotMapResult(0.78540, 0.63860)),
            entry(3.51145, new ShotMapResult(0.82903, 0.66153)),
            entry(3.56119, new ShotMapResult(0.87266, 0.68588)),
            entry(3.62445, new ShotMapResult(0.91630, 0.71194)),
            entry(3.70279, new ShotMapResult(0.95993, 0.74007)),
            entry(3.79828, new ShotMapResult(1.00356, 0.77072)),
            entry(3.91369, new ShotMapResult(1.04720, 0.80445)),
            entry(4.05274, new ShotMapResult(1.09083, 0.84202)),
            entry(4.22053, new ShotMapResult(1.13446, 0.88442)),
            entry(4.42415, new ShotMapResult(1.17810, 0.93304)),
            entry(4.67379, new ShotMapResult(1.22173, 0.98982)),
            entry(4.98457, new ShotMapResult(1.26536, 1.05760)),
            entry(5.37993, new ShotMapResult(1.30900, 1.14078)),
            entry(5.89807, new ShotMapResult(1.35263, 1.24637)),
            entry(6.60469, new ShotMapResult(1.39626, 1.38621)),
            entry(7.61583, new ShotMapResult(1.43990, 1.58041)),
            entry(9.10935, new ShotMapResult(1.48353, 1.85711))
        );
        put(
            2.00000,
            entry(4.13573, new ShotMapResult(0.78540, 0.71972)),
            entry(4.17303, new ShotMapResult(0.82903, 0.74693)),
            entry(4.22533, new ShotMapResult(0.87266, 0.77577)),
            entry(4.29388, new ShotMapResult(0.91630, 0.80658)),
            entry(4.38042, new ShotMapResult(0.95993, 0.83978)),
            entry(4.48733, new ShotMapResult(1.00356, 0.87588)),
            entry(4.61779, new ShotMapResult(1.04720, 0.91557)),
            entry(4.77612, new ShotMapResult(1.09083, 0.95969)),
            entry(4.96820, new ShotMapResult(1.13446, 1.00940)),
            entry(5.20228, new ShotMapResult(1.17810, 1.06626)),
            entry(5.49013, new ShotMapResult(1.22173, 1.13250)),
            entry(5.84909, new ShotMapResult(1.26536, 1.21129)),
            entry(6.30565, new ShotMapResult(1.30900, 1.30745)),
            entry(6.90166, new ShotMapResult(1.35263, 1.42835)),
            entry(7.70450, new ShotMapResult(1.39626, 1.58551)),
            entry(8.81616, new ShotMapResult(1.43990, 1.79517)),
            entry(10.33811, new ShotMapResult(1.48353, 2.06991))
        );
        put(
            2.50000,
            entry(4.72166, new ShotMapResult(0.78540, 0.79289)),
            entry(4.75901, new ShotMapResult(0.82903, 0.82385)),
            entry(4.81375, new ShotMapResult(0.87266, 0.85663)),
            entry(4.88722, new ShotMapResult(0.91630, 0.89160)),
            entry(4.98135, new ShotMapResult(0.95993, 0.92924)),
            entry(5.09876, new ShotMapResult(1.00356, 0.97013)),
            entry(5.24302, new ShotMapResult(1.04720, 1.01501)),
            entry(5.41894, new ShotMapResult(1.09083, 1.06483)),
            entry(5.63315, new ShotMapResult(1.13446, 1.12088)),
            entry(5.89483, new ShotMapResult(1.17810, 1.18487)),
            entry(6.21706, new ShotMapResult(1.22173, 1.25919)),
            entry(6.61885, new ShotMapResult(1.26536, 1.34725)),
            entry(7.12859, new ShotMapResult(1.30900, 1.45400)),
            entry(7.78921, new ShotMapResult(1.35263, 1.58669)),
            entry(8.66391, new ShotMapResult(1.39626, 1.75538)),
            entry(9.83064, new ShotMapResult(1.43990, 1.97099)),
            entry(11.32540, new ShotMapResult(1.48353, 2.23411))
        );
        put(
            3.00000,
            entry(5.25541, new ShotMapResult(0.78540, 0.86007)),
            entry(5.29294, new ShotMapResult(0.82903, 0.89442)),
            entry(5.35008, new ShotMapResult(0.87266, 0.93074)),
            entry(5.42826, new ShotMapResult(0.91630, 0.96946)),
            entry(5.52956, new ShotMapResult(0.95993, 1.01109)),
            entry(5.65685, new ShotMapResult(1.00356, 1.05627)),
            entry(5.81401, new ShotMapResult(1.04720, 1.10579)),
            entry(6.00634, new ShotMapResult(1.09083, 1.16071)),
            entry(6.24106, new ShotMapResult(1.13446, 1.22238)),
            entry(6.52817, new ShotMapResult(1.17810, 1.29263)),
            entry(6.88174, new ShotMapResult(1.22173, 1.37397)),
            entry(7.32191, new ShotMapResult(1.26536, 1.46989)),
            entry(7.87785, new ShotMapResult(1.30900, 1.58527)),
            entry(8.59123, new ShotMapResult(1.35263, 1.72675)),
            entry(9.51680, new ShotMapResult(1.39626, 1.90232)),
            entry(10.70583, new ShotMapResult(1.43990, 2.11755)),
            entry(12.14939, new ShotMapResult(1.48353, 2.36565))
        );
        put(
            3.50000,
            entry(5.75096, new ShotMapResult(0.78540, 0.92251)),
            entry(5.78876, new ShotMapResult(0.82903, 0.95996)),
            entry(5.84826, new ShotMapResult(0.87266, 0.99953)),
            entry(5.93098, new ShotMapResult(0.91630, 1.04168)),
            entry(6.03913, new ShotMapResult(0.95993, 1.08696)),
            entry(6.17579, new ShotMapResult(1.00356, 1.13604)),
            entry(6.34516, new ShotMapResult(1.04720, 1.18979)),
            entry(6.55293, new ShotMapResult(1.09083, 1.24930)),
            entry(6.80683, new ShotMapResult(1.13446, 1.31601)),
            entry(7.11753, new ShotMapResult(1.17810, 1.39182)),
            entry(7.49979, new ShotMapResult(1.22173, 1.47928)),
            entry(7.97434, new ShotMapResult(1.26536, 1.58185)),
            entry(8.57004, new ShotMapResult(1.30900, 1.70414)),
            entry(9.32537, new ShotMapResult(1.35263, 1.85185)),
            entry(10.28417, new ShotMapResult(1.39626, 2.03060)),
            entry(11.47342, new ShotMapResult(1.43990, 2.24151)),
            entry(12.85775, new ShotMapResult(1.48353, 2.47410))
        );
        put(
            4.00000,
            entry(6.21734, new ShotMapResult(0.78540, 0.98103)),
            entry(6.25546, new ShotMapResult(0.82903, 1.02137)),
            entry(6.31728, new ShotMapResult(0.87266, 1.06396)),
            entry(6.40438, new ShotMapResult(0.91630, 1.10928)),
            entry(6.51910, new ShotMapResult(0.95993, 1.15792)),
            entry(6.66472, new ShotMapResult(1.00356, 1.21060)),
            entry(6.84569, new ShotMapResult(1.04720, 1.26821)),
            entry(7.06805, new ShotMapResult(1.09083, 1.33190)),
            entry(7.33998, new ShotMapResult(1.13446, 1.40316)),
            entry(7.67259, new ShotMapResult(1.17810, 1.48392)),
            entry(8.08109, new ShotMapResult(1.22173, 1.57670)),
            entry(8.58624, new ShotMapResult(1.26536, 1.68484)),
            entry(9.21564, new ShotMapResult(1.30900, 1.81248)),
            entry(10.00313, new ShotMapResult(1.35263, 1.96423)),
            entry(10.98093, new ShotMapResult(1.39626, 2.14335)),
            entry(12.15638, new ShotMapResult(1.43990, 2.34769)),
            entry(13.48097, new ShotMapResult(1.48353, 2.56548))
        );
        put(
            4.50000,
            entry(6.66083, new ShotMapResult(0.78540, 1.03624)),
            entry(6.69928, new ShotMapResult(0.82903, 1.07929)),
            entry(6.76334, new ShotMapResult(0.87266, 1.12470)),
            entry(6.85466, new ShotMapResult(0.91630, 1.17298)),
            entry(6.97570, new ShotMapResult(0.95993, 1.22474)),
            entry(7.12989, new ShotMapResult(1.00356, 1.28075)),
            entry(7.32191, new ShotMapResult(1.04720, 1.34192)),
            entry(7.55810, new ShotMapResult(1.09083, 1.40944)),
            entry(7.84695, new ShotMapResult(1.13446, 1.48480)),
            entry(8.19991, new ShotMapResult(1.17810, 1.56994)),
            entry(8.63230, new ShotMapResult(1.22173, 1.66732)),
            entry(9.16442, new ShotMapResult(1.26536, 1.78003)),
            entry(9.82181, new ShotMapResult(1.30900, 1.91165)),
            entry(10.63283, new ShotMapResult(1.35263, 2.06558)),
            entry(11.61853, new ShotMapResult(1.39626, 2.24301)),
            entry(12.77182, new ShotMapResult(1.43990, 2.43963)),
            entry(14.03946, new ShotMapResult(1.48353, 2.64375))
        );
        put(
            5.00000,
            entry(7.08598, new ShotMapResult(0.78540, 1.08857)),
            entry(7.12459, new ShotMapResult(0.82893, 1.13405)),
            entry(7.19055, new ShotMapResult(0.87246, 1.18199)),
            entry(7.28552, new ShotMapResult(0.91598, 1.23290)),
            entry(7.41203, new ShotMapResult(0.95951, 1.28743)),
            entry(7.57362, new ShotMapResult(1.00304, 1.34633)),
            entry(7.77512, new ShotMapResult(1.04657, 1.41056)),
            entry(8.02301, new ShotMapResult(1.09010, 1.48129)),
            entry(8.32593, new ShotMapResult(1.13363, 1.56000)),
            entry(8.69531, new ShotMapResult(1.17715, 1.64858)),
            entry(9.14615, new ShotMapResult(1.22068, 1.74932)),
            entry(9.69758, new ShotMapResult(1.26421, 1.86499)),
            entry(10.37229, new ShotMapResult(1.30774, 1.99851)),
            entry(11.19271, new ShotMapResult(1.35127, 2.15209)),
            entry(12.17056, new ShotMapResult(1.39480, 2.32539)),
            entry(13.29020, new ShotMapResult(1.43833, 2.51304)),
            entry(14.50000, new ShotMapResult(1.48185, 2.70435))
        );
        put(
            5.50000,
            entry(7.49623, new ShotMapResult(0.78540, 1.13834)),
            entry(7.53375, new ShotMapResult(0.82784, 1.18501)),
            entry(7.59893, new ShotMapResult(0.87028, 1.23408)),
            entry(7.69333, new ShotMapResult(0.91272, 1.28606)),
            entry(7.81930, new ShotMapResult(0.95516, 1.34153)),
            entry(7.98015, new ShotMapResult(0.99759, 1.40122)),
            entry(8.18032, new ShotMapResult(1.04003, 1.46599)),
            entry(8.42575, new ShotMapResult(1.08247, 1.53690)),
            entry(8.72419, new ShotMapResult(1.12491, 1.61527)),
            entry(9.08572, new ShotMapResult(1.16735, 1.70270)),
            entry(9.52324, new ShotMapResult(1.20979, 1.80112)),
            entry(10.05261, new ShotMapResult(1.25223, 1.91270)),
            entry(10.69195, new ShotMapResult(1.29467, 2.03966)),
            entry(11.45837, new ShotMapResult(1.33711, 2.18348)),
            entry(12.36040, new ShotMapResult(1.37955, 2.34366)),
            entry(13.38678, new ShotMapResult(1.42199, 2.51607)),
            entry(14.50000, new ShotMapResult(1.46443, 2.69269))
        );
        put(
            6.00000,
            entry(7.89427, new ShotMapResult(0.78540, 1.18579)),
            entry(7.93053, new ShotMapResult(0.82673, 1.23340)),
            entry(7.99458, new ShotMapResult(0.86806, 1.28334)),
            entry(8.08785, new ShotMapResult(0.90939, 1.33608)),
            entry(8.21249, new ShotMapResult(0.95071, 1.39218)),
            entry(8.37154, new ShotMapResult(0.99204, 1.45229)),
            entry(8.56907, new ShotMapResult(1.03337, 1.51722)),
            entry(8.81043, new ShotMapResult(1.07470, 1.58790)),
            entry(9.10251, new ShotMapResult(1.11603, 1.66547)),
            entry(9.45412, new ShotMapResult(1.15736, 1.75131)),
            entry(9.87620, new ShotMapResult(1.19869, 1.84699)),
            entry(10.38187, new ShotMapResult(1.24002, 1.95424)),
            entry(10.98558, new ShotMapResult(1.28135, 2.07471)),
            entry(11.70049, new ShotMapResult(1.32268, 2.20940)),
            entry(12.53305, new ShotMapResult(1.36401, 2.35776)),
            entry(13.47529, new ShotMapResult(1.40533, 2.51663)),
            entry(14.50000, new ShotMapResult(1.44666, 2.67994))
        );
        put(
            6.50000,
            entry(8.28226, new ShotMapResult(0.78540, 1.23114)),
            entry(8.32038, new ShotMapResult(0.82827, 1.28273)),
            entry(8.39014, new ShotMapResult(0.87115, 1.33691)),
            entry(8.49316, new ShotMapResult(0.91402, 1.39421)),
            entry(8.63199, new ShotMapResult(0.95690, 1.45528)),
            entry(8.81022, new ShotMapResult(0.99977, 1.52088)),
            entry(9.03267, new ShotMapResult(1.04265, 1.59191)),
            entry(9.30568, new ShotMapResult(1.08552, 1.66945)),
            entry(9.63740, new ShotMapResult(1.12840, 1.75477)),
            entry(10.03802, new ShotMapResult(1.17127, 1.84937)),
            entry(10.51988, new ShotMapResult(1.21415, 1.95487)),
            entry(11.09676, new ShotMapResult(1.25702, 2.07284)),
            entry(11.78188, new ShotMapResult(1.29990, 2.20437)),
            entry(12.58323, new ShotMapResult(1.34277, 2.34923)),
            entry(13.49662, new ShotMapResult(1.38565, 2.50489)),
            entry(14.50000, new ShotMapResult(1.42852, 2.66603))
        );
        put(
            7.00000,
            entry(8.66199, new ShotMapResult(0.78540, 1.27451)),
            entry(8.69835, new ShotMapResult(0.82704, 1.32659)),
            entry(8.76608, new ShotMapResult(0.86867, 1.38114)),
            entry(8.86662, new ShotMapResult(0.91031, 1.43865)),
            entry(9.00224, new ShotMapResult(0.95195, 1.49972)),
            entry(9.17614, new ShotMapResult(0.99358, 1.56501)),
            entry(9.39263, new ShotMapResult(1.03522, 1.63534)),
            entry(9.65725, new ShotMapResult(1.07686, 1.71163)),
            entry(9.97703, new ShotMapResult(1.11849, 1.79497)),
            entry(10.36060, new ShotMapResult(1.16013, 1.88657)),
            entry(10.81813, new ShotMapResult(1.20177, 1.98773)),
            entry(11.36074, new ShotMapResult(1.24340, 2.09964)),
            entry(11.99880, new ShotMapResult(1.28504, 2.22306)),
            entry(12.73862, new ShotMapResult(1.32668, 2.35772)),
            entry(13.57759, new ShotMapResult(1.36832, 2.50166)),
            entry(14.50000, new ShotMapResult(1.40995, 2.65089))
        );
        put(
            7.50000,
            entry(9.03496, new ShotMapResult(0.78540, 1.31603)),
            entry(9.07295, new ShotMapResult(0.82865, 1.37219)),
            entry(9.14651, new ShotMapResult(0.87190, 1.43105)),
            entry(9.25727, new ShotMapResult(0.91515, 1.49320)),
            entry(9.40788, new ShotMapResult(0.95840, 1.55930)),
            entry(9.60208, new ShotMapResult(1.00165, 1.63012)),
            entry(9.84489, new ShotMapResult(1.04490, 1.70656)),
            entry(10.14279, new ShotMapResult(1.08815, 1.78965)),
            entry(10.50386, new ShotMapResult(1.13140, 1.88057)),
            entry(10.93778, new ShotMapResult(1.17465, 1.98056)),
            entry(11.45533, new ShotMapResult(1.21791, 2.09081)),
            entry(12.06710, new ShotMapResult(1.26116, 2.21215)),
            entry(12.78055, new ShotMapResult(1.30441, 2.34456)),
            entry(13.59558, new ShotMapResult(1.34766, 2.48648)),
            entry(14.50000, new ShotMapResult(1.39091, 2.63441))
        );
        put(
            8.00000,
            entry(9.40245, new ShotMapResult(0.78540, 1.35578)),
            entry(9.43801, new ShotMapResult(0.82725, 1.41195)),
            entry(9.50840, new ShotMapResult(0.86910, 1.47065)),
            entry(9.61501, new ShotMapResult(0.91095, 1.53241)),
            entry(9.76012, new ShotMapResult(0.95281, 1.59782)),
            entry(9.94697, new ShotMapResult(0.99466, 1.66755)),
            entry(10.17989, new ShotMapResult(1.03651, 1.74239)),
            entry(10.46440, new ShotMapResult(1.07836, 1.82319)),
            entry(10.80725, new ShotMapResult(1.12021, 1.91091)),
            entry(11.21639, new ShotMapResult(1.16207, 2.00655)),
            entry(11.70052, new ShotMapResult(1.20392, 2.11101)),
            entry(12.26804, new ShotMapResult(1.24577, 2.22489)),
            entry(12.92493, new ShotMapResult(1.28762, 2.34813)),
            entry(13.67169, new ShotMapResult(1.32947, 2.47954)),
            entry(14.50000, new ShotMapResult(1.37133, 2.61650))
        );
        put(
            8.50000,
            entry(9.76563, new ShotMapResult(0.78540, 1.39384)),
            entry(9.80240, new ShotMapResult(0.82892, 1.45416)),
            entry(9.87855, new ShotMapResult(0.87243, 1.51725)),
            entry(9.99564, new ShotMapResult(0.91595, 1.58369)),
            entry(10.15627, new ShotMapResult(0.95947, 1.65416)),
            entry(10.36419, new ShotMapResult(1.00299, 1.72940)),
            entry(10.62439, new ShotMapResult(1.04651, 1.81027)),
            entry(10.94316, new ShotMapResult(1.09003, 1.89771)),
            entry(11.32807, new ShotMapResult(1.13354, 1.99268)),
            entry(11.78761, new ShotMapResult(1.17706, 2.09612)),
            entry(12.33038, new ShotMapResult(1.22058, 2.20871)),
            entry(12.96323, new ShotMapResult(1.26410, 2.33056)),
            entry(13.68837, new ShotMapResult(1.30762, 2.46075)),
            entry(14.50000, new ShotMapResult(1.35114, 2.59701))
        );
        put(
            9.00000,
            entry(10.12553, new ShotMapResult(0.78540, 1.43024)),
            entry(10.15900, new ShotMapResult(0.82731, 1.49003)),
            entry(10.23054, new ShotMapResult(0.86922, 1.55235)),
            entry(10.34139, new ShotMapResult(0.91113, 1.61773)),
            entry(10.49370, new ShotMapResult(0.95305, 1.68673)),
            entry(10.69061, new ShotMapResult(0.99496, 1.76002)),
            entry(10.93625, new ShotMapResult(1.03687, 1.83829)),
            entry(11.23580, new ShotMapResult(1.07878, 1.92231)),
            entry(11.59539, new ShotMapResult(1.12069, 2.01286)),
            entry(12.02183, new ShotMapResult(1.16261, 2.11064)),
            entry(12.52191, new ShotMapResult(1.20452, 2.21616)),
            entry(13.10112, new ShotMapResult(1.24643, 2.32948)),
            entry(13.76166, new ShotMapResult(1.28834, 2.44992)),
            entry(14.50000, new ShotMapResult(1.33025, 2.57579))
        );
        put(
            9.50000,
            entry(10.48308, new ShotMapResult(0.78540, 1.46502)),
            entry(10.51706, new ShotMapResult(0.82900, 1.52902)),
            entry(10.59400, new ShotMapResult(0.87259, 1.59574)),
            entry(10.71520, new ShotMapResult(0.91619, 1.66578)),
            entry(10.88311, new ShotMapResult(0.95979, 1.73977)),
            entry(11.10125, new ShotMapResult(1.00339, 1.81844)),
            entry(11.37432, new ShotMapResult(1.04699, 1.90254)),
            entry(11.70806, new ShotMapResult(1.09058, 1.99285)),
            entry(12.10909, new ShotMapResult(1.13418, 2.09011)),
            entry(12.58431, new ShotMapResult(1.17778, 2.19489)),
            entry(13.13980, new ShotMapResult(1.22138, 2.30738)),
            entry(13.77893, new ShotMapResult(1.26498, 2.42712)),
            entry(14.50000, new ShotMapResult(1.30858, 2.55266))
        );
        put(
            10.00000,
            entry(10.83920, new ShotMapResult(0.78540, 1.49820)),
            entry(10.86882, new ShotMapResult(0.82711, 1.56100)),
            entry(10.93934, new ShotMapResult(0.86883, 1.62622)),
            entry(11.05170, new ShotMapResult(0.91054, 1.69439)),
            entry(11.20778, new ShotMapResult(0.95226, 1.76603)),
            entry(11.41041, new ShotMapResult(0.99397, 1.84175)),
            entry(11.66329, new ShotMapResult(1.03569, 1.92214)),
            entry(11.97097, new ShotMapResult(1.07740, 2.00783)),
            entry(12.33864, new ShotMapResult(1.11912, 2.09939)),
            entry(12.77167, new ShotMapResult(1.16083, 2.19724)),
            entry(13.27485, new ShotMapResult(1.20255, 2.30153)),
            entry(13.85114, new ShotMapResult(1.24426, 2.41192)),
            entry(14.50000, new ShotMapResult(1.28598, 2.52738))
        );
        put(
            10.50000,
            entry(11.19474, new ShotMapResult(0.78540, 1.52977)),
            entry(11.22383, new ShotMapResult(0.82875, 1.59672)),
            entry(11.29889, new ShotMapResult(0.87211, 1.66624)),
            entry(11.42084, new ShotMapResult(0.91547, 1.73891)),
            entry(11.59173, new ShotMapResult(0.95882, 1.81531)),
            entry(11.81467, new ShotMapResult(1.00218, 1.89609)),
            entry(12.09372, new ShotMapResult(1.04553, 1.98186)),
            entry(12.43379, new ShotMapResult(1.08889, 2.07323)),
            entry(12.84020, new ShotMapResult(1.13224, 2.17069)),
            entry(13.31805, new ShotMapResult(1.17560, 2.27448)),
            entry(13.87107, new ShotMapResult(1.21895, 2.38441)),
            entry(14.50000, new ShotMapResult(1.26231, 2.49965))
        );
        put(
            11.00000,
            entry(11.55057, new ShotMapResult(0.78540, 1.55973)),
            entry(11.57403, new ShotMapResult(0.82649, 1.62462)),
            entry(11.64040, new ShotMapResult(0.86757, 1.69172)),
            entry(11.75020, new ShotMapResult(0.90866, 1.76151)),
            entry(11.90485, new ShotMapResult(0.94975, 1.83447)),
            entry(12.10665, new ShotMapResult(0.99084, 1.91110)),
            entry(12.35864, new ShotMapResult(1.03193, 1.99190)),
            entry(12.66449, new ShotMapResult(1.07301, 2.07732)),
            entry(13.02820, new ShotMapResult(1.11410, 2.16773)),
            entry(13.45366, new ShotMapResult(1.15519, 2.26331)),
            entry(13.94388, new ShotMapResult(1.19628, 2.36395)),
            entry(14.50000, new ShotMapResult(1.23737, 2.46911))
        );
        put(
            11.50000,
            entry(11.90748, new ShotMapResult(0.78775, 1.59180)),
            entry(11.93130, new ShotMapResult(0.83007, 1.66028)),
            entry(12.00243, new ShotMapResult(0.87238, 1.73105)),
            entry(12.12129, new ShotMapResult(0.91469, 1.80462)),
            entry(12.28933, new ShotMapResult(0.95701, 1.88149)),
            entry(12.50895, new ShotMapResult(0.99932, 1.96219)),
            entry(12.78332, new ShotMapResult(1.04163, 2.04718)),
            entry(13.11612, new ShotMapResult(1.08395, 2.13686)),
            entry(13.51119, new ShotMapResult(1.12626, 2.23150)),
            entry(13.97186, new ShotMapResult(1.16857, 2.33110)),
            entry(14.50000, new ShotMapResult(1.21089, 2.43524))
        );
        put(
            12.00000,
            entry(12.26594, new ShotMapResult(0.79222, 1.62582)),
            entry(12.29199, new ShotMapResult(0.83558, 1.69775)),
            entry(12.36966, new ShotMapResult(0.87895, 1.77203)),
            entry(12.49926, new ShotMapResult(0.92232, 1.84918)),
            entry(12.68224, new ShotMapResult(0.96568, 1.92975)),
            entry(12.92104, new ShotMapResult(1.00905, 2.01421)),
            entry(13.21881, new ShotMapResult(1.05241, 2.10301)),
            entry(13.57913, new ShotMapResult(1.09578, 2.19646)),
            entry(14.00539, new ShotMapResult(1.13914, 2.29466)),
            entry(14.50000, new ShotMapResult(1.18251, 2.39737))
        );
        put(
            12.50000,
            entry(12.62665, new ShotMapResult(0.79701, 1.65899)),
            entry(12.64907, new ShotMapResult(0.83642, 1.72581)),
            entry(12.71580, new ShotMapResult(0.87583, 1.79445)),
            entry(12.82676, new ShotMapResult(0.91524, 1.86530)),
            entry(12.98269, new ShotMapResult(0.95465, 1.93874)),
            entry(13.18503, new ShotMapResult(0.99407, 2.01512)),
            entry(13.43572, new ShotMapResult(1.03348, 2.09474)),
            entry(13.73703, new ShotMapResult(1.07289, 2.17782)),
            entry(14.09119, new ShotMapResult(1.11230, 2.26444)),
            entry(14.50000, new ShotMapResult(1.15172, 2.35451))
        );
        put(
            13.00000,
            entry(12.99041, new ShotMapResult(0.80215, 1.69132)),
            entry(13.01380, new ShotMapResult(0.84159, 1.75971)),
            entry(13.08327, new ShotMapResult(0.88104, 1.82981)),
            entry(13.19853, new ShotMapResult(0.92048, 1.90203)),
            entry(13.36014, new ShotMapResult(0.95993, 1.97672)),
            entry(13.56934, new ShotMapResult(0.99937, 2.05418)),
            entry(13.82781, new ShotMapResult(1.03882, 2.13467)),
            entry(14.13744, new ShotMapResult(1.07826, 2.21833)),
            entry(14.50000, new ShotMapResult(1.11771, 2.30515))
        );
        put(
            13.50000,
            entry(13.35804, new ShotMapResult(0.80768, 1.72284)),
            entry(13.38158, new ShotMapResult(0.84646, 1.79151)),
            entry(13.45138, new ShotMapResult(0.88524, 1.86173)),
            entry(13.56691, new ShotMapResult(0.92403, 1.93385)),
            entry(13.72847, new ShotMapResult(0.96281, 2.00820)),
            entry(13.93695, new ShotMapResult(1.00159, 2.08503)),
            entry(14.19365, new ShotMapResult(1.04038, 2.16452)),
            entry(14.50000, new ShotMapResult(1.07916, 2.24677))
        );
        put(
            14.00000,
            entry(13.73040, new ShotMapResult(0.81363, 1.75354)),
            entry(13.75230, new ShotMapResult(0.85027, 1.81971)),
            entry(13.81711, new ShotMapResult(0.88691, 1.88714)),
            entry(13.92409, new ShotMapResult(0.92355, 1.95610)),
            entry(14.07321, new ShotMapResult(0.96019, 2.02686)),
            entry(14.26492, new ShotMapResult(0.99683, 2.09960)),
            entry(14.50000, new ShotMapResult(1.03346, 2.17445))
        );
        put(
            14.50000,
            entry(14.10846, new ShotMapResult(0.82006, 1.78342)),
            entry(14.13361, new ShotMapResult(0.85853, 1.85432)),
            entry(14.20783, new ShotMapResult(0.89701, 1.92647)),
            entry(14.33004, new ShotMapResult(0.93549, 2.00017)),
            entry(14.50000, new ShotMapResult(0.97397, 2.07568))
        );
        put(
            15.00000,
            entry(14.49326, new ShotMapResult(0.82700, 1.81248)),
            entry(14.50000, new ShotMapResult(0.84642, 1.84883))
        );
    }
}
