// This file is autogenerated at 'scripts/shooter_calcs/main.py'.
package robot.subsystems.shooter.math;

import robot.subsystems.shooter.DataTypes.ShotMapResult;

import static java.util.Map.entry;

public final class HubShotMap extends ShotMap {
    public HubShotMap() {
        put(
            0.80000,
            entry(5.66728, new ShotMapResult(1.34864, 0.66836)),
            entry(5.89404, new ShotMapResult(1.39228, 0.79673)),
            entry(6.37940, new ShotMapResult(1.43591, 0.96727)),
            entry(7.30444, new ShotMapResult(1.47954, 1.21651)),
            entry(7.42258, new ShotMapResult(1.48353, 1.24532))
        );
        put(
            0.90000,
            entry(5.70588, new ShotMapResult(1.32167, 0.66824)),
            entry(5.88879, new ShotMapResult(1.36530, 0.78220)),
            entry(6.27187, new ShotMapResult(1.40893, 0.92765)),
            entry(6.96671, new ShotMapResult(1.45257, 1.12810)),
            entry(7.77663, new ShotMapResult(1.48353, 1.32718))
        );
        put(
            1.00000,
            entry(5.74880, new ShotMapResult(1.29504, 0.66811)),
            entry(5.89718, new ShotMapResult(1.33867, 0.77097)),
            entry(6.20702, new ShotMapResult(1.38230, 0.89827)),
            entry(6.75087, new ShotMapResult(1.42594, 1.06592)),
            entry(7.68587, new ShotMapResult(1.46957, 1.30368))
        );
        put(
            1.10000,
            entry(5.85372, new ShotMapResult(1.29504, 0.72270)),
            entry(6.05087, new ShotMapResult(1.33867, 0.82751)),
            entry(6.40762, new ShotMapResult(1.38230, 0.95788)),
            entry(7.00134, new ShotMapResult(1.42594, 1.12981)),
            entry(7.98888, new ShotMapResult(1.46957, 1.37195)),
            entry(8.42883, new ShotMapResult(1.48353, 1.47087))
        );
        put(
            1.20000,
            entry(5.84729, new ShotMapResult(1.24293, 0.66781)),
            entry(5.94347, new ShotMapResult(1.28656, 0.75486)),
            entry(6.15486, new ShotMapResult(1.33020, 0.85786)),
            entry(6.51607, new ShotMapResult(1.37383, 0.98518)),
            entry(7.09760, new ShotMapResult(1.41746, 1.15112)),
            entry(8.03664, new ShotMapResult(1.46109, 1.38057)),
            entry(8.72933, new ShotMapResult(1.48353, 1.53455))
        );
        put(
            1.30000,
            entry(5.90272, new ShotMapResult(1.21750, 0.66764)),
            entry(5.96303, new ShotMapResult(1.25551, 0.73780)),
            entry(6.09816, new ShotMapResult(1.29351, 0.81752)),
            entry(6.32212, new ShotMapResult(1.33151, 0.91064)),
            entry(6.66117, new ShotMapResult(1.36952, 1.02297)),
            entry(7.16184, new ShotMapResult(1.40752, 1.16369)),
            entry(7.90482, new ShotMapResult(1.44553, 1.34736)),
            entry(9.01445, new ShotMapResult(1.48353, 1.59371))
        );
        put(
            1.40000,
            entry(5.96216, new ShotMapResult(1.19252, 0.66746)),
            entry(6.01902, new ShotMapResult(1.23615, 0.74396)),
            entry(6.16593, new ShotMapResult(1.27979, 0.83170)),
            entry(6.42112, new ShotMapResult(1.32342, 0.93571)),
            entry(6.82087, new ShotMapResult(1.36705, 1.06389)),
            entry(7.43287, new ShotMapResult(1.41069, 1.22934)),
            entry(8.37878, new ShotMapResult(1.45432, 1.45328)),
            entry(9.28537, new ShotMapResult(1.48353, 1.64886))
        );
        put(
            1.50000,
            entry(6.03840, new ShotMapResult(1.19252, 0.70700)),
            entry(6.12334, new ShotMapResult(1.23615, 0.78450)),
            entry(6.29622, new ShotMapResult(1.27979, 0.87372)),
            entry(6.57738, new ShotMapResult(1.32342, 0.97972)),
            entry(7.00493, new ShotMapResult(1.36705, 1.11049)),
            entry(7.64773, new ShotMapResult(1.41069, 1.27900)),
            entry(8.62449, new ShotMapResult(1.45432, 1.50542))
        );
        put(
            1.60000,
            entry(6.09178, new ShotMapResult(1.15108, 0.67786)),
            entry(6.12484, new ShotMapResult(1.19264, 0.74464)),
            entry(6.22678, new ShotMapResult(1.23419, 0.81928)),
            entry(6.40684, new ShotMapResult(1.27575, 0.90474)),
            entry(6.68315, new ShotMapResult(1.31730, 1.00532)),
            entry(7.08758, new ShotMapResult(1.35886, 1.12757)),
            entry(7.67478, new ShotMapResult(1.40042, 1.28170)),
            entry(8.53512, new ShotMapResult(1.44197, 1.48310)),
            entry(9.78901, new ShotMapResult(1.48353, 1.74888))
        );
        put(
            1.70000,
            entry(6.16355, new ShotMapResult(1.15108, 0.71272)),
            entry(6.21801, new ShotMapResult(1.19264, 0.78029)),
            entry(6.33969, new ShotMapResult(1.23419, 0.85602)),
            entry(6.53912, new ShotMapResult(1.27575, 0.94291)),
            entry(6.83560, new ShotMapResult(1.31730, 1.04531)),
            entry(7.26201, new ShotMapResult(1.35886, 1.16977)),
            entry(7.87343, new ShotMapResult(1.40042, 1.32638)),
            entry(8.75789, new ShotMapResult(1.44197, 1.52975)),
            entry(10.02370, new ShotMapResult(1.48353, 1.79443))
        );
        put(
            1.80000,
            entry(6.24298, new ShotMapResult(1.15108, 0.74596)),
            entry(6.31591, new ShotMapResult(1.19264, 0.81437)),
            entry(6.45508, new ShotMapResult(1.23419, 0.89123)),
            entry(6.67209, new ShotMapResult(1.27575, 0.97956)),
            entry(6.98715, new ShotMapResult(1.31730, 1.08373)),
            entry(7.43396, new ShotMapResult(1.35886, 1.21032)),
            entry(8.06776, new ShotMapResult(1.40042, 1.36922)),
            entry(8.97372, new ShotMapResult(1.44197, 1.57422)),
            entry(10.24815, new ShotMapResult(1.48353, 1.83740))
        );
        put(
            1.90000,
            entry(6.29787, new ShotMapResult(1.10849, 0.71347)),
            entry(6.32660, new ShotMapResult(1.15016, 0.77632)),
            entry(6.41475, new ShotMapResult(1.19183, 0.84566)),
            entry(6.56883, new ShotMapResult(1.23350, 0.92370)),
            entry(6.80128, new ShotMapResult(1.27517, 1.01349)),
            entry(7.13312, new ShotMapResult(1.31684, 1.11946)),
            entry(7.59877, new ShotMapResult(1.35852, 1.24818)),
            entry(8.25356, new ShotMapResult(1.40019, 1.40936)),
            entry(9.17990, new ShotMapResult(1.44186, 1.61603)),
            entry(10.46315, new ShotMapResult(1.48353, 1.87801))
        );
        put(
            2.00000,
            entry(6.37082, new ShotMapResult(1.10849, 0.74331)),
            entry(6.41514, new ShotMapResult(1.15016, 0.80687)),
            entry(6.51788, new ShotMapResult(1.19183, 0.87713)),
            entry(6.68637, new ShotMapResult(1.23350, 0.95632)),
            entry(6.93378, new ShotMapResult(1.27517, 1.04752)),
            entry(7.28180, new ShotMapResult(1.31684, 1.15518)),
            entry(7.76535, new ShotMapResult(1.35852, 1.28583)),
            entry(8.43940, new ShotMapResult(1.40019, 1.44894)),
            entry(9.38277, new ShotMapResult(1.44186, 1.65662)),
            entry(10.66940, new ShotMapResult(1.48353, 1.91649))
        );
        put(
            2.10000,
            entry(6.44843, new ShotMapResult(1.10849, 0.77200)),
            entry(6.50657, new ShotMapResult(1.15016, 0.83630)),
            entry(6.62253, new ShotMapResult(1.19183, 0.90750)),
            entry(6.80429, new ShotMapResult(1.23350, 0.98783)),
            entry(7.06566, new ShotMapResult(1.27517, 1.08042)),
            entry(7.42891, new ShotMapResult(1.31684, 1.18972)),
            entry(7.92930, new ShotMapResult(1.35852, 1.32220)),
            entry(8.62121, new ShotMapResult(1.40019, 1.48707)),
            entry(9.57962, new ShotMapResult(1.44186, 1.69548)),
            entry(10.86755, new ShotMapResult(1.48353, 1.95301))
        );
        put(
            2.20000,
            entry(6.51130, new ShotMapResult(1.07362, 0.74943)),
            entry(6.53648, new ShotMapResult(1.11461, 0.80886)),
            entry(6.61341, new ShotMapResult(1.15560, 0.87371)),
            entry(6.74677, new ShotMapResult(1.19659, 0.94566)),
            entry(6.94529, new ShotMapResult(1.23758, 1.02694)),
            entry(7.22332, new ShotMapResult(1.27857, 1.12064)),
            entry(7.60338, new ShotMapResult(1.31957, 1.23115)),
            entry(8.12034, new ShotMapResult(1.36056, 1.36472)),
            entry(8.82629, new ShotMapResult(1.40155, 1.52995)),
            entry(9.78919, new ShotMapResult(1.44254, 1.73655)),
            entry(11.05820, new ShotMapResult(1.48353, 1.98775))
        );
        put(
            2.30000,
            entry(6.58499, new ShotMapResult(1.07362, 0.77564)),
            entry(6.62184, new ShotMapResult(1.11461, 0.83570)),
            entry(6.70986, new ShotMapResult(1.15560, 0.90134)),
            entry(6.85423, new ShotMapResult(1.19659, 0.97424)),
            entry(7.06419, new ShotMapResult(1.23758, 1.05665)),
            entry(7.35450, new ShotMapResult(1.27857, 1.15169)),
            entry(7.74808, new ShotMapResult(1.31957, 1.26371)),
            entry(8.27985, new ShotMapResult(1.36056, 1.39889)),
            entry(9.00090, new ShotMapResult(1.40155, 1.56549)),
            entry(9.97497, new ShotMapResult(1.44254, 1.77228)),
            entry(11.24186, new ShotMapResult(1.48353, 2.02083))
        );
        put(
            2.40000,
            entry(6.65599, new ShotMapResult(1.05384, 0.77334)),
            entry(6.68237, new ShotMapResult(1.09681, 0.83472)),
            entry(6.76300, new ShotMapResult(1.13978, 0.90172)),
            entry(6.90282, new ShotMapResult(1.18275, 0.97609)),
            entry(7.11113, new ShotMapResult(1.22571, 1.06018)),
            entry(7.40319, new ShotMapResult(1.26868, 1.15723)),
            entry(7.80297, new ShotMapResult(1.31165, 1.27183)),
            entry(8.34740, new ShotMapResult(1.35462, 1.41052)),
            entry(9.09094, new ShotMapResult(1.39759, 1.58205)),
            entry(10.10160, new ShotMapResult(1.44056, 1.79568)),
            entry(11.41904, new ShotMapResult(1.48353, 2.05240))
        );
        put(
            2.50000,
            entry(6.72992, new ShotMapResult(1.05384, 0.79763)),
            entry(6.76670, new ShotMapResult(1.09681, 0.85965)),
            entry(6.85729, new ShotMapResult(1.13978, 0.92743)),
            entry(7.00711, new ShotMapResult(1.18275, 1.00274)),
            entry(7.22590, new ShotMapResult(1.22571, 1.08792)),
            entry(7.52932, new ShotMapResult(1.26868, 1.18625)),
            entry(7.94166, new ShotMapResult(1.31165, 1.30230)),
            entry(8.49984, new ShotMapResult(1.35462, 1.44248)),
            entry(9.25710, new ShotMapResult(1.39759, 1.61520)),
            entry(10.27701, new ShotMapResult(1.44056, 1.82874)),
            entry(11.59018, new ShotMapResult(1.48353, 2.08256))
        );
        put(
            2.60000,
            entry(6.80179, new ShotMapResult(1.03635, 0.79706)),
            entry(6.82453, new ShotMapResult(1.07700, 0.85435)),
            entry(6.89378, new ShotMapResult(1.11766, 0.91632)),
            entry(7.01305, new ShotMapResult(1.15831, 0.98426)),
            entry(7.18881, new ShotMapResult(1.19896, 1.05990)),
            entry(7.43142, new ShotMapResult(1.23961, 1.14551)),
            entry(7.75663, new ShotMapResult(1.28027, 1.24419)),
            entry(8.18792, new ShotMapResult(1.32092, 1.36019)),
            entry(8.75941, new ShotMapResult(1.36157, 1.49924)),
            entry(9.51738, new ShotMapResult(1.40222, 1.66831)),
            entry(10.51130, new ShotMapResult(1.44288, 1.87324)),
            entry(11.75567, new ShotMapResult(1.48353, 2.11142))
        );
        put(
            2.70000,
            entry(6.87580, new ShotMapResult(1.03635, 0.81974)),
            entry(6.90704, new ShotMapResult(1.07700, 0.87761)),
            entry(6.98450, new ShotMapResult(1.11766, 0.94026)),
            entry(7.11202, new ShotMapResult(1.15831, 1.00901)),
            entry(7.29638, new ShotMapResult(1.19896, 1.08557)),
            entry(7.54822, new ShotMapResult(1.23961, 1.17223)),
            entry(7.88355, new ShotMapResult(1.28027, 1.27210)),
            entry(8.32594, new ShotMapResult(1.32092, 1.38937)),
            entry(8.90920, new ShotMapResult(1.36157, 1.52963)),
            entry(9.67802, new ShotMapResult(1.40222, 1.69945)),
            entry(10.67764, new ShotMapResult(1.44288, 1.90382)),
            entry(11.91589, new ShotMapResult(1.48353, 2.13908))
        );
        put(
            2.80000,
            entry(6.94819, new ShotMapResult(1.02083, 0.82054)),
            entry(6.97184, new ShotMapResult(1.06289, 0.87948)),
            entry(7.04389, new ShotMapResult(1.10495, 0.94322)),
            entry(7.16799, new ShotMapResult(1.14702, 1.01311)),
            entry(7.35093, new ShotMapResult(1.18908, 1.09094)),
            entry(7.60355, new ShotMapResult(1.23115, 1.17906)),
            entry(7.94233, new ShotMapResult(1.27321, 1.28067)),
            entry(8.39171, new ShotMapResult(1.31527, 1.40013)),
            entry(8.98689, new ShotMapResult(1.35734, 1.54322)),
            entry(9.77442, new ShotMapResult(1.39940, 1.71674)),
            entry(10.80080, new ShotMapResult(1.44147, 1.92568)),
            entry(12.07118, new ShotMapResult(1.48353, 2.16561))
        );
        put(
            2.90000,
            entry(7.02216, new ShotMapResult(1.02083, 0.84184)),
            entry(7.05348, new ShotMapResult(1.06289, 0.90136)),
            entry(7.13300, new ShotMapResult(1.10495, 0.96577)),
            entry(7.26467, new ShotMapResult(1.14702, 1.03645)),
            entry(7.45557, new ShotMapResult(1.18908, 1.11518)),
            entry(7.71680, new ShotMapResult(1.23115, 1.20432)),
            entry(8.06505, new ShotMapResult(1.27321, 1.30706)),
            entry(8.52482, new ShotMapResult(1.31527, 1.42771)),
            entry(9.13090, new ShotMapResult(1.35734, 1.57190)),
            entry(9.92814, new ShotMapResult(1.39940, 1.74600)),
            entry(10.95874, new ShotMapResult(1.44147, 1.95417)),
            entry(12.22184, new ShotMapResult(1.48353, 2.19109))
        );
        put(
            3.00000,
            entry(7.09481, new ShotMapResult(1.00698, 0.84372)),
            entry(7.11935, new ShotMapResult(1.05030, 0.90426)),
            entry(7.19410, new ShotMapResult(1.09363, 0.96971)),
            entry(7.32286, new ShotMapResult(1.13695, 1.04149)),
            entry(7.51271, new ShotMapResult(1.18027, 1.12141)),
            entry(7.77494, new ShotMapResult(1.22359, 1.21192)),
            entry(8.12666, new ShotMapResult(1.26692, 1.31629)),
            entry(8.59314, new ShotMapResult(1.31024, 1.43895)),
            entry(9.21032, new ShotMapResult(1.35356, 1.58569)),
            entry(10.02450, new ShotMapResult(1.39688, 1.76304)),
            entry(11.07842, new ShotMapResult(1.44021, 1.97503)),
            entry(12.36816, new ShotMapResult(1.48353, 2.21559))
        );
        put(
            3.10000,
            entry(7.16864, new ShotMapResult(1.00698, 0.86383)),
            entry(7.20014, new ShotMapResult(1.05030, 0.92494)),
            entry(7.28172, new ShotMapResult(1.09363, 0.99106)),
            entry(7.41748, new ShotMapResult(1.13695, 1.06360)),
            entry(7.61474, new ShotMapResult(1.18027, 1.14440)),
            entry(7.88503, new ShotMapResult(1.22359, 1.23589)),
            entry(8.24565, new ShotMapResult(1.26692, 1.34134)),
            entry(8.72187, new ShotMapResult(1.31024, 1.46512)),
            entry(9.34915, new ShotMapResult(1.35356, 1.61285)),
            entry(10.17198, new ShotMapResult(1.39688, 1.79062)),
            entry(11.22881, new ShotMapResult(1.44021, 2.00168)),
            entry(12.51040, new ShotMapResult(1.48353, 2.23917))
        );
        put(
            3.20000,
            entry(7.24138, new ShotMapResult(0.99459, 0.86659)),
            entry(7.26271, new ShotMapResult(1.03533, 0.92333)),
            entry(7.32752, new ShotMapResult(1.07608, 0.98420)),
            entry(7.43854, new ShotMapResult(1.11682, 1.05028)),
            entry(7.60081, new ShotMapResult(1.15757, 1.12294)),
            entry(7.82224, new ShotMapResult(1.19831, 1.20393)),
            entry(8.11451, new ShotMapResult(1.23906, 1.29556)),
            entry(8.49441, new ShotMapResult(1.27980, 1.40085)),
            entry(8.98542, new ShotMapResult(1.32055, 1.52369)),
            entry(9.61876, new ShotMapResult(1.36129, 1.66881)),
            entry(10.43037, new ShotMapResult(1.40204, 1.84076)),
            entry(11.44595, new ShotMapResult(1.44278, 2.04085)),
            entry(12.64880, new ShotMapResult(1.48353, 2.26189))
        );
        put(
            3.30000,
            entry(7.31500, new ShotMapResult(0.99459, 0.88565)),
            entry(7.34215, new ShotMapResult(1.03533, 0.94291)),
            entry(7.41271, new ShotMapResult(1.07608, 1.00437)),
            entry(7.52962, new ShotMapResult(1.11682, 1.07112)),
            entry(7.69811, new ShotMapResult(1.15757, 1.14453)),
            entry(7.92624, new ShotMapResult(1.19831, 1.22636)),
            entry(8.22585, new ShotMapResult(1.23906, 1.31890)),
            entry(8.61378, new ShotMapResult(1.27980, 1.42515)),
            entry(9.11336, new ShotMapResult(1.32055, 1.54893)),
            entry(9.75510, new ShotMapResult(1.36129, 1.69476)),
            entry(10.57302, new ShotMapResult(1.40204, 1.86677)),
            entry(11.58923, new ShotMapResult(1.44278, 2.06565)),
            entry(12.78357, new ShotMapResult(1.48353, 2.28380))
        );
        put(
            3.40000,
            entry(7.38769, new ShotMapResult(0.98345, 0.88913)),
            entry(7.40973, new ShotMapResult(1.02512, 0.94724)),
            entry(7.47668, new ShotMapResult(1.06679, 1.00958)),
            entry(7.59135, new ShotMapResult(1.10847, 1.07723)),
            entry(7.75897, new ShotMapResult(1.15014, 1.15161)),
            entry(7.98769, new ShotMapResult(1.19181, 1.23451)),
            entry(8.28954, new ShotMapResult(1.23349, 1.32827)),
            entry(8.68172, new ShotMapResult(1.27516, 1.43594)),
            entry(9.18810, new ShotMapResult(1.31684, 1.56142)),
            entry(9.83982, new ShotMapResult(1.35851, 1.70927)),
            entry(10.67132, new ShotMapResult(1.40018, 1.88363)),
            entry(11.70401, new ShotMapResult(1.44186, 2.08491)),
            entry(12.91493, new ShotMapResult(1.48353, 2.30495))
        );
        put(
            3.50000,
            entry(7.46104, new ShotMapResult(0.98345, 0.90726)),
            entry(7.48842, new ShotMapResult(1.02512, 0.96590)),
            entry(7.56068, new ShotMapResult(1.06679, 1.02882)),
            entry(7.68084, new ShotMapResult(1.10847, 1.09713)),
            entry(7.85428, new ShotMapResult(1.15014, 1.17224)),
            entry(8.08931, new ShotMapResult(1.19181, 1.25595)),
            entry(8.39809, new ShotMapResult(1.23349, 1.35058)),
            entry(8.79785, new ShotMapResult(1.27516, 1.45916)),
            entry(9.31227, new ShotMapResult(1.31684, 1.58550)),
            entry(9.97170, new ShotMapResult(1.35851, 1.73395)),
            entry(10.80861, new ShotMapResult(1.40018, 1.90824)),
            entry(11.84101, new ShotMapResult(1.44186, 2.10820)),
            entry(13.04306, new ShotMapResult(1.48353, 2.32538))
        );
        put(
            3.60000,
            entry(7.53361, new ShotMapResult(0.97340, 0.91132)),
            entry(7.55634, new ShotMapResult(1.01591, 0.97078)),
            entry(7.62537, new ShotMapResult(1.05842, 1.03454)),
            entry(7.74361, new ShotMapResult(1.10093, 1.10372)),
            entry(7.91642, new ShotMapResult(1.14344, 1.17977)),
            entry(8.15220, new ShotMapResult(1.18595, 1.26449)),
            entry(8.46328, new ShotMapResult(1.22846, 1.36028)),
            entry(8.86721, new ShotMapResult(1.27098, 1.47019)),
            entry(9.38811, new ShotMapResult(1.31349, 1.59809)),
            entry(10.05681, new ShotMapResult(1.35600, 1.74837)),
            entry(10.90595, new ShotMapResult(1.39851, 1.92468)),
            entry(11.95254, new ShotMapResult(1.44102, 2.12659)),
            entry(13.16814, new ShotMapResult(1.48353, 2.34512))
        );
        put(
            3.70000,
            entry(7.60665, new ShotMapResult(0.97340, 0.92863)),
            entry(7.63429, new ShotMapResult(1.01591, 0.98861)),
            entry(7.70825, new ShotMapResult(1.05842, 1.05295)),
            entry(7.83161, new ShotMapResult(1.10093, 1.12277)),
            entry(8.00990, new ShotMapResult(1.14344, 1.19953)),
            entry(8.25165, new ShotMapResult(1.18595, 1.28503)),
            entry(8.56930, new ShotMapResult(1.22846, 1.38166)),
            entry(8.98040, new ShotMapResult(1.27098, 1.49243)),
            entry(9.50883, new ShotMapResult(1.31349, 1.62111)),
            entry(10.18458, new ShotMapResult(1.35600, 1.77189)),
            entry(11.03832, new ShotMapResult(1.39851, 1.94801)),
            entry(12.08383, new ShotMapResult(1.44102, 2.14852)),
            entry(13.29032, new ShotMapResult(1.48353, 2.36423))
        );
        put(
            3.80000,
            entry(7.68005, new ShotMapResult(0.97340, 0.94563)),
            entry(7.71235, new ShotMapResult(1.01591, 1.00612)),
            entry(7.79103, new ShotMapResult(1.05842, 1.07102)),
            entry(7.91934, new ShotMapResult(1.10093, 1.14149)),
            entry(8.10294, new ShotMapResult(1.14344, 1.21894)),
            entry(8.35047, new ShotMapResult(1.18595, 1.30521)),
            entry(8.67449, new ShotMapResult(1.22846, 1.40265)),
            entry(9.09253, new ShotMapResult(1.27098, 1.51424)),
            entry(9.62819, new ShotMapResult(1.31349, 1.64366)),
            entry(10.31058, new ShotMapResult(1.35600, 1.79487)),
            entry(11.16840, new ShotMapResult(1.39851, 1.97073)),
            entry(12.21242, new ShotMapResult(1.44102, 2.16979)),
            entry(13.40976, new ShotMapResult(1.48353, 2.38272))
        );
        put(
            3.90000,
            entry(7.75152, new ShotMapResult(0.96008, 0.94396)),
            entry(7.77525, new ShotMapResult(1.00370, 1.00538)),
            entry(7.84733, new ShotMapResult(1.04732, 1.07120)),
            entry(7.97076, new ShotMapResult(1.09094, 1.14260)),
            entry(8.15111, new ShotMapResult(1.13456, 1.22103)),
            entry(8.39709, new ShotMapResult(1.17819, 1.30838)),
            entry(8.72142, new ShotMapResult(1.22181, 1.40703)),
            entry(9.14206, new ShotMapResult(1.26543, 1.52006)),
            entry(9.68324, new ShotMapResult(1.30905, 1.65123)),
            entry(10.37498, new ShotMapResult(1.35267, 1.80461)),
            entry(11.24676, new ShotMapResult(1.39629, 1.98311)),
            entry(12.30907, new ShotMapResult(1.43991, 2.18507)),
            entry(13.52659, new ShotMapResult(1.48353, 2.40063))
        );
        put(
            4.00000,
            entry(7.82406, new ShotMapResult(0.96008, 0.96020)),
            entry(7.85215, new ShotMapResult(1.00370, 1.02213)),
            entry(7.92866, new ShotMapResult(1.04732, 1.08852)),
            entry(8.05675, new ShotMapResult(1.09094, 1.16053)),
            entry(8.24213, new ShotMapResult(1.13456, 1.23965)),
            entry(8.49362, new ShotMapResult(1.17819, 1.32773)),
            entry(8.82403, new ShotMapResult(1.22181, 1.42716)),
            entry(9.25127, new ShotMapResult(1.26543, 1.54097)),
            entry(9.79929, new ShotMapResult(1.30905, 1.67282)),
            entry(10.49717, new ShotMapResult(1.35267, 1.82657)),
            entry(11.37245, new ShotMapResult(1.39629, 2.00472)),
            entry(12.43271, new ShotMapResult(1.43991, 2.20518)),
            entry(13.64096, new ShotMapResult(1.48353, 2.41800))
        );
        put(
            4.10000,
            entry(7.89682, new ShotMapResult(0.96008, 0.97616)),
            entry(7.92907, new ShotMapResult(1.00370, 1.03860)),
            entry(8.00985, new ShotMapResult(1.04732, 1.10554)),
            entry(8.14245, new ShotMapResult(1.09094, 1.17817)),
            entry(8.33272, new ShotMapResult(1.13456, 1.25796)),
            entry(8.58957, new ShotMapResult(1.17819, 1.34676)),
            entry(8.92589, new ShotMapResult(1.22181, 1.44696)),
            entry(9.35952, new ShotMapResult(1.26543, 1.56152)),
            entry(9.91409, new ShotMapResult(1.30905, 1.69400)),
            entry(10.61776, new ShotMapResult(1.35267, 1.84804)),
            entry(11.49610, new ShotMapResult(1.39629, 2.02579)),
            entry(12.55396, new ShotMapResult(1.43991, 2.22471)),
            entry(13.75296, new ShotMapResult(1.48353, 2.43483))
        );
        put(
            4.20000,
            entry(7.96974, new ShotMapResult(0.96008, 0.99185)),
            entry(8.00598, new ShotMapResult(1.00370, 1.05479)),
            entry(8.09087, new ShotMapResult(1.04732, 1.12229)),
            entry(8.22784, new ShotMapResult(1.09094, 1.19553)),
            entry(8.42286, new ShotMapResult(1.13456, 1.27597)),
            entry(8.68493, new ShotMapResult(1.17819, 1.36549)),
            entry(9.02699, new ShotMapResult(1.22181, 1.46642)),
            entry(9.46683, new ShotMapResult(1.26543, 1.58170)),
            entry(10.02769, new ShotMapResult(1.30905, 1.71477)),
            entry(10.73678, new ShotMapResult(1.35267, 1.86905)),
            entry(11.61775, new ShotMapResult(1.39629, 2.04633)),
            entry(12.67293, new ShotMapResult(1.43991, 2.24370)),
            entry(13.86273, new ShotMapResult(1.48353, 2.45117))
        );
        put(
            4.30000,
            entry(8.03996, new ShotMapResult(0.94504, 0.98630)),
            entry(8.06129, new ShotMapResult(0.98646, 1.04517)),
            entry(8.12589, new ShotMapResult(1.02789, 1.10782)),
            entry(8.23600, new ShotMapResult(1.06931, 1.17518)),
            entry(8.39576, new ShotMapResult(1.11073, 1.24840)),
            entry(8.61151, new ShotMapResult(1.15215, 1.32886)),
            entry(8.89237, new ShotMapResult(1.19357, 1.41833)),
            entry(9.25087, new ShotMapResult(1.23500, 1.51897)),
            entry(9.70364, new ShotMapResult(1.27642, 1.63339)),
            entry(10.27136, new ShotMapResult(1.31784, 1.76451)),
            entry(10.97660, new ShotMapResult(1.35926, 1.91491)),
            entry(11.83621, new ShotMapResult(1.40069, 2.08535)),
            entry(12.84666, new ShotMapResult(1.44211, 2.27239)),
            entry(13.97037, new ShotMapResult(1.48353, 2.46704))
        );
        put(
            4.40000,
            entry(8.11181, new ShotMapResult(0.94504, 1.00133)),
            entry(8.13660, new ShotMapResult(0.98646, 1.06065)),
            entry(8.20477, new ShotMapResult(1.02789, 1.12380)),
            entry(8.31866, new ShotMapResult(1.06931, 1.19171)),
            entry(8.48249, new ShotMapResult(1.11073, 1.26550)),
            entry(8.70269, new ShotMapResult(1.15215, 1.34659)),
            entry(8.98844, new ShotMapResult(1.19357, 1.43671)),
            entry(9.35225, new ShotMapResult(1.23500, 1.53800)),
            entry(9.81058, new ShotMapResult(1.27642, 1.65302)),
            entry(10.38368, new ShotMapResult(1.31784, 1.78456)),
            entry(11.09311, new ShotMapResult(1.35926, 1.93500)),
            entry(11.95402, new ShotMapResult(1.40069, 2.10479)),
            entry(12.96100, new ShotMapResult(1.44211, 2.29024)),
            entry(14.07597, new ShotMapResult(1.48353, 2.48244))
        );
        put(
            4.50000,
            entry(8.18375, new ShotMapResult(0.94504, 1.01612)),
            entry(8.21186, new ShotMapResult(0.98646, 1.07590)),
            entry(8.28349, new ShotMapResult(1.02789, 1.13955)),
            entry(8.40104, new ShotMapResult(1.06931, 1.20798)),
            entry(8.56884, new ShotMapResult(1.11073, 1.28235)),
            entry(8.79339, new ShotMapResult(1.15215, 1.36405)),
            entry(9.08389, new ShotMapResult(1.19357, 1.45481)),
            entry(9.45286, new ShotMapResult(1.23500, 1.55673)),
            entry(9.91657, new ShotMapResult(1.27642, 1.67231)),
            entry(10.49481, new ShotMapResult(1.31784, 1.80423)),
            entry(11.20811, new ShotMapResult(1.35926, 1.95465)),
            entry(12.07000, new ShotMapResult(1.40069, 2.12375)),
            entry(13.07331, new ShotMapResult(1.44211, 2.30761)),
            entry(14.17963, new ShotMapResult(1.48353, 2.49742))
        );
        put(
            4.60000,
            entry(8.25575, new ShotMapResult(0.94504, 1.03069)),
            entry(8.28706, new ShotMapResult(0.98646, 1.09093)),
            entry(8.36202, new ShotMapResult(1.02789, 1.15506)),
            entry(8.48314, new ShotMapResult(1.06931, 1.22402)),
            entry(8.65481, new ShotMapResult(1.11073, 1.29896)),
            entry(8.88359, new ShotMapResult(1.15215, 1.38125)),
            entry(9.17874, new ShotMapResult(1.19357, 1.47262)),
            entry(9.55272, new ShotMapResult(1.23500, 1.57515)),
            entry(10.02162, new ShotMapResult(1.27642, 1.69127)),
            entry(10.60475, new ShotMapResult(1.31784, 1.82353)),
            entry(11.32164, new ShotMapResult(1.35926, 1.97388)),
            entry(12.18420, new ShotMapResult(1.40069, 2.14225)),
            entry(13.18367, new ShotMapResult(1.44211, 2.32452)),
            entry(14.28143, new ShotMapResult(1.48353, 2.51197))
        );
        put(
            4.70000,
            entry(8.32582, new ShotMapResult(0.93250, 1.02733)),
            entry(8.34823, new ShotMapResult(0.97489, 1.08841)),
            entry(8.41605, new ShotMapResult(1.01727, 1.15337)),
            entry(8.53159, new ShotMapResult(1.05966, 1.22316)),
            entry(8.69911, new ShotMapResult(1.10205, 1.29893)),
            entry(8.92517, new ShotMapResult(1.14443, 1.38212)),
            entry(9.21910, new ShotMapResult(1.18682, 1.47447)),
            entry(9.59358, new ShotMapResult(1.22921, 1.57812)),
            entry(10.06509, new ShotMapResult(1.27160, 1.69555)),
            entry(10.65346, new ShotMapResult(1.31398, 1.82938)),
            entry(11.37880, new ShotMapResult(1.35637, 1.98163)),
            entry(12.25335, new ShotMapResult(1.39876, 2.15216)),
            entry(13.26771, new ShotMapResult(1.44114, 2.33668)),
            entry(14.38146, new ShotMapResult(1.48353, 2.52613))
        );
        put(
            4.80000,
            entry(8.39698, new ShotMapResult(0.93250, 1.04134)),
            entry(8.42239, new ShotMapResult(0.97489, 1.10287)),
            entry(8.49337, new ShotMapResult(1.01727, 1.16831)),
            entry(8.61230, new ShotMapResult(1.05966, 1.23862)),
            entry(8.78352, new ShotMapResult(1.10205, 1.31495)),
            entry(9.01364, new ShotMapResult(1.14443, 1.39872)),
            entry(9.31202, new ShotMapResult(1.18682, 1.49166)),
            entry(9.69131, new ShotMapResult(1.22921, 1.59589)),
            entry(10.16778, new ShotMapResult(1.27160, 1.71382)),
            entry(10.76075, new ShotMapResult(1.31398, 1.84794)),
            entry(11.48935, new ShotMapResult(1.35637, 2.00008)),
            entry(12.36424, new ShotMapResult(1.39876, 2.16985)),
            entry(13.37454, new ShotMapResult(1.44114, 2.35276)),
            entry(14.47979, new ShotMapResult(1.48353, 2.53990))
        );
        put(
            4.90000,
            entry(8.46816, new ShotMapResult(0.93250, 1.05516)),
            entry(8.49621, new ShotMapResult(0.97466, 1.11680)),
            entry(8.56950, new ShotMapResult(1.01683, 1.18233)),
            entry(8.69043, new ShotMapResult(1.05899, 1.25271)),
            entry(8.86331, new ShotMapResult(1.10116, 1.32905)),
            entry(9.09468, new ShotMapResult(1.14332, 1.41276)),
            entry(9.39369, new ShotMapResult(1.18549, 1.50550)),
            entry(9.77263, new ShotMapResult(1.22765, 1.60931)),
            entry(10.24722, new ShotMapResult(1.26982, 1.72651)),
            entry(10.83588, new ShotMapResult(1.31198, 1.85944)),
            entry(11.55664, new ShotMapResult(1.35415, 2.00974)),
            entry(12.41924, new ShotMapResult(1.39631, 2.17697)),
            entry(13.41311, new ShotMapResult(1.43848, 2.35681)),
            entry(14.50000, new ShotMapResult(1.48064, 2.54080))
        );
        put(
            5.00000,
            entry(8.53934, new ShotMapResult(0.93250, 1.06878)),
            entry(8.56982, new ShotMapResult(0.97438, 1.13043)),
            entry(8.64509, new ShotMapResult(1.01627, 1.19595)),
            entry(8.76756, new ShotMapResult(1.05815, 1.26626)),
            entry(8.94148, new ShotMapResult(1.10003, 1.34247)),
            entry(9.17324, new ShotMapResult(1.14192, 1.42592)),
            entry(9.47175, new ShotMapResult(1.18380, 1.51824)),
            entry(9.84889, new ShotMapResult(1.22568, 1.62137)),
            entry(10.31970, new ShotMapResult(1.26757, 1.73751)),
            entry(10.90170, new ShotMapResult(1.30945, 1.86885)),
            entry(11.61181, new ShotMapResult(1.35133, 2.01691)),
            entry(12.45909, new ShotMapResult(1.39321, 2.18120)),
            entry(13.43370, new ShotMapResult(1.43510, 2.35766)),
            entry(14.50000, new ShotMapResult(1.47698, 2.53835))
        );
        put(
            5.10000,
            entry(8.60911, new ShotMapResult(0.92197, 1.06712)),
            entry(8.63171, new ShotMapResult(0.96438, 1.12914)),
            entry(8.70006, new ShotMapResult(1.00679, 1.19496)),
            entry(8.81633, new ShotMapResult(1.04920, 1.26549)),
            entry(8.98455, new ShotMapResult(1.09161, 1.34184)),
            entry(9.21091, new ShotMapResult(1.13402, 1.42533)),
            entry(9.50414, new ShotMapResult(1.17643, 1.51760)),
            entry(9.87592, new ShotMapResult(1.21884, 1.62055)),
            entry(10.34115, new ShotMapResult(1.26125, 1.73638)),
            entry(10.91727, new ShotMapResult(1.30366, 1.86729)),
            entry(11.62141, new ShotMapResult(1.34607, 2.01484)),
            entry(12.46328, new ShotMapResult(1.38849, 2.17868)),
            entry(13.43428, new ShotMapResult(1.43090, 2.35494)),
            entry(14.50000, new ShotMapResult(1.47331, 2.53584))
        );
        put(
            5.20000,
            entry(8.67962, new ShotMapResult(0.92197, 1.08026)),
            entry(8.70448, new ShotMapResult(0.96409, 1.14229)),
            entry(8.77464, new ShotMapResult(1.00622, 1.20808)),
            entry(8.89227, new ShotMapResult(1.04835, 1.27853)),
            entry(9.06135, new ShotMapResult(1.09047, 1.35472)),
            entry(9.28792, new ShotMapResult(1.13260, 1.43795)),
            entry(9.58048, new ShotMapResult(1.17473, 1.52977)),
            entry(9.95030, new ShotMapResult(1.21686, 1.63203)),
            entry(10.41167, new ShotMapResult(1.25898, 1.74681)),
            entry(10.98117, new ShotMapResult(1.30111, 1.87618)),
            entry(11.67492, new ShotMapResult(1.34324, 2.02157)),
            entry(12.50198, new ShotMapResult(1.38536, 2.18259)),
            entry(13.45435, new ShotMapResult(1.42749, 2.35559)),
            entry(14.50000, new ShotMapResult(1.46962, 2.53329))
        );
        put(
            5.30000,
            entry(8.75010, new ShotMapResult(0.92197, 1.09324)),
            entry(8.77711, new ShotMapResult(0.96381, 1.15525)),
            entry(8.84897, new ShotMapResult(1.00565, 1.22099)),
            entry(8.96785, new ShotMapResult(1.04749, 1.29135)),
            entry(9.13766, new ShotMapResult(1.08933, 1.36737)),
            entry(9.36432, new ShotMapResult(1.13118, 1.45031)),
            entry(9.65607, new ShotMapResult(1.17302, 1.54168)),
            entry(10.02380, new ShotMapResult(1.21486, 1.64323)),
            entry(10.48120, new ShotMapResult(1.25670, 1.75696)),
            entry(11.04402, new ShotMapResult(1.29854, 1.88479)),
            entry(11.72744, new ShotMapResult(1.34039, 2.02803)),
            entry(12.53994, new ShotMapResult(1.38223, 2.18630)),
            entry(13.47406, new ShotMapResult(1.42407, 2.35613)),
            entry(14.50000, new ShotMapResult(1.46591, 2.53068))
        );
        put(
            5.40000,
            entry(8.82055, new ShotMapResult(0.92197, 1.10604)),
            entry(8.84960, new ShotMapResult(0.96352, 1.16803)),
            entry(8.92304, new ShotMapResult(1.00508, 1.23372)),
            entry(9.04306, new ShotMapResult(1.04663, 1.30397)),
            entry(9.21349, new ShotMapResult(1.08819, 1.37981)),
            entry(9.44011, new ShotMapResult(1.12975, 1.46244)),
            entry(9.73093, new ShotMapResult(1.17130, 1.55333)),
            entry(10.09644, new ShotMapResult(1.21286, 1.65417)),
            entry(10.54975, new ShotMapResult(1.25441, 1.76682)),
            entry(11.10585, new ShotMapResult(1.29597, 1.89312)),
            entry(11.77901, new ShotMapResult(1.33752, 2.03426)),
            entry(12.57718, new ShotMapResult(1.37908, 2.18981)),
            entry(13.49343, new ShotMapResult(1.42064, 2.35655)),
            entry(14.50000, new ShotMapResult(1.46219, 2.52802))
        );
        put(
            5.50000,
            entry(8.89096, new ShotMapResult(0.92197, 1.11868)),
            entry(8.92193, new ShotMapResult(0.96323, 1.18063)),
            entry(8.99686, new ShotMapResult(1.00450, 1.24626)),
            entry(9.11790, new ShotMapResult(1.04577, 1.31639)),
            entry(9.28884, new ShotMapResult(1.08704, 1.39202)),
            entry(9.51531, new ShotMapResult(1.12831, 1.47433)),
            entry(9.80507, new ShotMapResult(1.16958, 1.56473)),
            entry(10.16824, new ShotMapResult(1.21085, 1.66483)),
            entry(10.61737, new ShotMapResult(1.25211, 1.77641)),
            entry(11.16669, new ShotMapResult(1.29338, 1.90118)),
            entry(11.82967, new ShotMapResult(1.33465, 2.04024)),
            entry(12.61373, new ShotMapResult(1.37592, 2.19315)),
            entry(13.51245, new ShotMapResult(1.41719, 2.35685)),
            entry(14.50000, new ShotMapResult(1.45846, 2.52531))
        );
        put(
            5.60000,
            entry(8.96132, new ShotMapResult(0.92197, 1.13115)),
            entry(8.99411, new ShotMapResult(0.96295, 1.19307)),
            entry(9.07043, new ShotMapResult(1.00393, 1.25861)),
            entry(9.19240, new ShotMapResult(1.04491, 1.32860)),
            entry(9.36373, new ShotMapResult(1.08588, 1.40402)),
            entry(9.58993, new ShotMapResult(1.12686, 1.48599)),
            entry(9.87851, new ShotMapResult(1.16784, 1.57588)),
            entry(10.23922, new ShotMapResult(1.20882, 1.67524)),
            entry(10.68408, new ShotMapResult(1.24980, 1.78574)),
            entry(11.22660, new ShotMapResult(1.29078, 1.90898)),
            entry(11.87946, new ShotMapResult(1.33176, 2.04599)),
            entry(12.64962, new ShotMapResult(1.37274, 2.19630)),
            entry(13.53114, new ShotMapResult(1.41372, 2.35705)),
            entry(14.50000, new ShotMapResult(1.45470, 2.52254))
        );
        put(
            5.70000,
            entry(9.03162, new ShotMapResult(0.92197, 1.14348)),
            entry(9.06614, new ShotMapResult(0.96266, 1.20533)),
            entry(9.14374, new ShotMapResult(1.00335, 1.27078)),
            entry(9.26654, new ShotMapResult(1.04404, 1.34063)),
            entry(9.43817, new ShotMapResult(1.08472, 1.41581)),
            entry(9.66399, new ShotMapResult(1.12541, 1.49743)),
            entry(9.95127, new ShotMapResult(1.16610, 1.58680)),
            entry(10.30941, new ShotMapResult(1.20679, 1.68539)),
            entry(10.74991, new ShotMapResult(1.24748, 1.79480)),
            entry(11.28558, new ShotMapResult(1.28817, 1.91653)),
            entry(11.92840, new ShotMapResult(1.32886, 2.05151)),
            entry(12.68488, new ShotMapResult(1.36955, 2.19928)),
            entry(13.54953, new ShotMapResult(1.41024, 2.35713)),
            entry(14.50000, new ShotMapResult(1.45093, 2.51973))
        );
        put(
            5.80000,
            entry(9.10186, new ShotMapResult(0.92197, 1.15565)),
            entry(9.13801, new ShotMapResult(0.96236, 1.21744)),
            entry(9.21681, new ShotMapResult(1.00276, 1.28278)),
            entry(9.34033, new ShotMapResult(1.04316, 1.35246)),
            entry(9.51216, new ShotMapResult(1.08356, 1.42739)),
            entry(9.73749, new ShotMapResult(1.12396, 1.50865)),
            entry(10.02336, new ShotMapResult(1.16436, 1.59747)),
            entry(10.37883, new ShotMapResult(1.20475, 1.69529)),
            entry(10.81488, new ShotMapResult(1.24515, 1.80361)),
            entry(11.34369, new ShotMapResult(1.28555, 1.92384)),
            entry(11.97653, new ShotMapResult(1.32595, 2.05681)),
            entry(12.71952, new ShotMapResult(1.36635, 2.20209)),
            entry(13.56761, new ShotMapResult(1.40675, 2.35710)),
            entry(14.50000, new ShotMapResult(1.44714, 2.51685))
        );
        put(
            5.87500,
            entry(9.15120, new ShotMapResult(0.90598, 1.14094)),
            entry(9.17325, new ShotMapResult(0.94739, 1.20336)),
            entry(9.23981, new ShotMapResult(0.98880, 1.26926)),
            entry(9.35260, new ShotMapResult(1.03020, 1.33942)),
            entry(9.51497, new ShotMapResult(1.07161, 1.41479)),
            entry(9.73195, new ShotMapResult(1.11302, 1.49645)),
            entry(10.01055, new ShotMapResult(1.15443, 1.58570)),
            entry(10.35990, new ShotMapResult(1.19584, 1.68398)),
            entry(10.79125, new ShotMapResult(1.23725, 1.79289)),
            entry(11.31732, new ShotMapResult(1.27866, 1.91392)),
            entry(11.95022, new ShotMapResult(1.32006, 2.04806)),
            entry(12.69718, new ShotMapResult(1.36147, 2.19500)),
            entry(13.55402, new ShotMapResult(1.40288, 2.35223)),
            entry(14.50000, new ShotMapResult(1.44429, 2.51466))
        );
        put(
            5.95000,
            entry(9.20325, new ShotMapResult(0.90598, 1.14978)),
            entry(9.22650, new ShotMapResult(0.94717, 1.21215)),
            entry(9.29392, new ShotMapResult(0.98836, 1.27796)),
            entry(9.40722, new ShotMapResult(1.02954, 1.34800)),
            entry(9.56969, new ShotMapResult(1.07073, 1.42318)),
            entry(9.78627, new ShotMapResult(1.11192, 1.50458)),
            entry(10.06380, new ShotMapResult(1.15311, 1.59342)),
            entry(10.41116, new ShotMapResult(1.19430, 1.69114)),
            entry(10.83922, new ShotMapResult(1.23549, 1.79925)),
            entry(11.36024, new ShotMapResult(1.27667, 1.91918)),
            entry(11.98582, new ShotMapResult(1.31786, 2.05186)),
            entry(12.72287, new ShotMapResult(1.35905, 2.19697)),
            entry(13.56747, new ShotMapResult(1.40024, 2.35212)),
            entry(14.50000, new ShotMapResult(1.44143, 2.51244))
        );
        put(
            6.00000,
            entry(9.23794, new ShotMapResult(0.90598, 1.15563)),
            entry(9.26196, new ShotMapResult(0.94702, 1.21796)),
            entry(9.32992, new ShotMapResult(0.98806, 1.28371)),
            entry(9.44354, new ShotMapResult(1.02910, 1.35367)),
            entry(9.60604, new ShotMapResult(1.07014, 1.42872)),
            entry(9.82233, new ShotMapResult(1.11118, 1.50993)),
            entry(10.09911, new ShotMapResult(1.15223, 1.59850)),
            entry(10.44511, new ShotMapResult(1.19327, 1.69584)),
            entry(10.87096, new ShotMapResult(1.23431, 1.80341)),
            entry(11.38860, new ShotMapResult(1.27535, 1.92261)),
            entry(12.00932, new ShotMapResult(1.31639, 2.05433)),
            entry(12.73982, new ShotMapResult(1.35743, 2.19824)),
            entry(13.57635, new ShotMapResult(1.39847, 2.35201)),
            entry(14.50000, new ShotMapResult(1.43951, 2.51094))
        );
    }
}
