"""
FRC 2026 shooter trajectory optimization.

This program uses the Sleipnir NLP solver to find the initial pitch and yaw for a game
piece to hit the 2026 FRC game's target given an initial velocity.

This optimization problem formulation uses direct transcription of the flight dynamics, including
air resistance.

Based on the 2022 trajectory optimization example code by Tyler Veness,
and 167's sleipnir code (thanks lol).
https://github.com/SleipnirGroup/Sleipnir/blob/main/examples/frc_2022_shooter/main.py
"""
import math
import numpy as np

from typing import TextIO
from shooter_calcs.internals import min_velocity, max_velocity, lerp, solve_fixed_pitch

delta_pitch = np.deg2rad(2.5)
max_pitch = np.deg2rad(85)


def iterate_distance(file: TextIO, distance: float, target_height: float):
    # Solves for shooting params at the minimum speed possible
    min_vel_solve = min_velocity(distance, target_height)
    if not min_vel_solve:
        raise Exception("Min vel solve failed")

    # Solve for shooting params at the maximum speed(14.5 m/s)
    max_vel_solve = max_velocity(distance, target_height, min_vel_solve)
    if not max_vel_solve:
        raise Exception("Max vel solve failed")

    # Solve for shooting params at the maximum hood angle(85 deg)
    stage_one_solve = solve_fixed_pitch(
        distance,
        target_height,
        (max_pitch + min_vel_solve.pitch_rad) / 2,
        min_vel_solve,
    )
    max_pitch_solve = solve_fixed_pitch(distance, target_height, max_pitch, stage_one_solve)
    if not max_pitch_solve:
        raise Exception("Max pitch solve failed")

    # Determines the "upper bound" shooting parameters.
    if max_pitch_solve.pitch_rad < max_vel_solve.pitch_rad:
        max_solve = max_pitch_solve
    else:
        max_solve = max_vel_solve

    # Writes the content to the file.
    prev_solve = min_vel_solve
    pitch_samples = math.ceil((max_solve.pitch_rad - min_vel_solve.pitch_rad) / delta_pitch)
    file.write(f"        put(\n")
    file.write(f"            {distance},\n")
    file.write(f"            {min_vel_solve.format()},\n")
    for i in range(1, pitch_samples - 1):
        pitch = lerp(min_vel_solve.pitch_rad, max_solve.pitch_rad, i / (pitch_samples - 1))
        solve = solve_fixed_pitch(distance, target_height, pitch, prev_solve)
        if solve and pitch + delta_pitch < max_solve.pitch_rad:
            prev_solve = solve
            file.write(f"            {solve.format()},\n")
        else:
            break
    file.write(f"            {max_solve.format()}\n")
    file.write("        );\n")


def write(
    name: str,
    target_height: float,
    min_distance: float,
    max_distance: float,
    distance_samples: int,
    distance_exponent: float
):
    filename = "../../src/main/java/robot/subsystems/shooter/math/" + name + ".java"
    with open(filename, "w") as file:
        file.write("// This file is autogenerated at 'scripts/shooter_calcs/main.py'. \n")
        file.write("package robot.subsystems.shooter.math;\n\n")
        file.write("import robot.subsystems.shooter.ShooterConsts.ShotMapResult;\n\n")
        file.write("import static java.util.Map.entry;\n\n")
        file.write(f"public final class {name} extends ShotMap " "{\n")
        file.write(f"   public {name}() " "{\n")
        for i in range(distance_samples):
            distance = lerp(
                min_distance,
                max_distance,
                (i / (distance_samples - 1)) ** distance_exponent,
            )
            iterate_distance(file, distance, target_height)
        file.write("  }\n")
        file.write("}\n")

if __name__ == "__main__":
    write(
        name="HubShotMap",
        target_height=72 * 0.0254,
        min_distance=0.29,
        max_distance=math.sqrt((8.062 / 2) ** 2 + ((158.1 + 47 / 2) * 0.0254) ** 2) + 8,
        distance_samples=25,
        distance_exponent=2,
    )
    write(
        name="GroundShotMap",
        target_height=0,
        min_distance=0.25,
        max_distance=math.sqrt(8.062 ** 2 + 16.54 ** 2) - 1,
        distance_samples=25,
        distance_exponent=1.5,
    )