package robot.constants;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;

import java.util.Map;
import java.util.OptionalInt;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj BorderLineTests = new ChoreoTraj(
	    "BorderLineTests",
	    OptionalInt.empty(),
	    4.35683,
	    new Pose2d(3.08779, 5.70991, Rotation2d.fromRadians(0)),
	    new Pose2d(0, 0, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj NewPath = new ChoreoTraj(
	    "NewPath",
	    OptionalInt.empty(),
	    4.97994,
	    new Pose2d(3.17442, 3.63336, Rotation2d.fromRadians(0)),
	    new Pose2d(7.49661, 2.12059, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj ShortPath = new ChoreoTraj(
	    "ShortPath",
	    OptionalInt.empty(),
	    1.02205,
	    new Pose2d(1, 2, Rotation2d.fromRadians(0)),
	    new Pose2d(1.6, 2, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj SimplePath = new ChoreoTraj(
	    "SimplePath",
	    OptionalInt.empty(),
	    7.61439,
	    new Pose2d(2.87727, 3.7144, Rotation2d.fromRadians(0)),
	    new Pose2d(0.54318, 5.94601, Rotation2d.fromRadians(0))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("BorderLineTests", BorderLineTests),
		Map.entry("NewPath", NewPath),
		Map.entry("ShortPath", ShortPath),
		Map.entry("SimplePath", SimplePath)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
