
package robot.constants;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj CenterGrab = new ChoreoTraj(
	    "CenterGrab",
	    OptionalInt.empty(),
	    3.31353,
	    new Pose2d(4.445, 0.795, Rotation2d.fromRadians(3.142)),
	    new Pose2d(7.9, 3.4, Rotation2d.fromRadians(-1.572))
	);
	public static final ChoreoTraj CenterLoopClose = new ChoreoTraj(
	    "CenterLoopClose",
	    OptionalInt.empty(),
	    6.45151,
	    new Pose2d(2.95, 1.05, Rotation2d.fromRadians(1.046)),
	    new Pose2d(3.75, 0.85, Rotation2d.fromRadians(1.323))
	);
	public static final ChoreoTraj CenterLoopFar = new ChoreoTraj(
	    "CenterLoopFar",
	    OptionalInt.empty(),
	    6.18278,
	    new Pose2d(4.45, 0.45, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(2.95, 1.05, Rotation2d.fromRadians(1.046))
	);
	public static final ChoreoTraj CenterScore = new ChoreoTraj(
	    "CenterScore",
	    OptionalInt.empty(),
	    3.21436,
	    new Pose2d(7.5, 1.9, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(2.7, 2.2, Rotation2d.fromRadians(0.765))
	);
	public static final ChoreoTraj CloseFuelGrab = new ChoreoTraj(
	    "CloseFuelGrab",
	    OptionalInt.empty(),
	    1.29793,
	    new Pose2d(2.5, 6.743, Rotation2d.fromRadians(-0.897)),
	    new Pose2d(0.74, 6.1, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj CloseFuelScore = new ChoreoTraj(
	    "CloseFuelScore",
	    OptionalInt.empty(),
	    0.78065,
	    new Pose2d(0.74, 6.1, Rotation2d.fromRadians(0)),
	    new Pose2d(1.359, 6.443, Rotation2d.fromRadians(-0.616))
	);
	public static final ChoreoTraj mirrored_CenterGrab = new ChoreoTraj(
	    "mirrored_CenterGrab",
	    OptionalInt.empty(),
	    3.31353,
	    new Pose2d(4.445, 7.248, Rotation2d.fromRadians(-3.142)),
	    new Pose2d(7.9, 4.643, Rotation2d.fromRadians(1.568))
	);
	public static final ChoreoTraj mirrored_CenterLoopClose = new ChoreoTraj(
	    "mirrored_CenterLoopClose",
	    OptionalInt.empty(),
	    6.82514,
	    new Pose2d(2.5, 6.743, Rotation2d.fromRadians(-0.897)),
	    new Pose2d(2.5, 6.743, Rotation2d.fromRadians(-0.897))
	);
	public static final ChoreoTraj mirrored_CenterLoopFar = new ChoreoTraj(
	    "mirrored_CenterLoopFar",
	    OptionalInt.empty(),
	    6.55942,
	    new Pose2d(4.416, 7.232, Rotation2d.fromRadians(-3.142)),
	    new Pose2d(2.5, 6.743, Rotation2d.fromRadians(-0.887))
	);
	public static final ChoreoTraj mirrored_CenterScore = new ChoreoTraj(
	    "mirrored_CenterScore",
	    OptionalInt.empty(),
	    3.21436,
	    new Pose2d(7.5, 6.143, Rotation2d.fromRadians(1.571)),
	    new Pose2d(2.7, 5.843, Rotation2d.fromRadians(-0.75))
	);
	public static final ChoreoTraj SubstationGrab = new ChoreoTraj(
	    "SubstationGrab",
	    OptionalInt.empty(),
	    1.25862,
	    new Pose2d(2.5, 1.3, Rotation2d.fromRadians(0.897)),
	    new Pose2d(0.72, 0.65, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj SubstationScore = new ChoreoTraj(
	    "SubstationScore",
	    OptionalInt.empty(),
	    1.13778,
	    new Pose2d(0.72, 0.65, Rotation2d.fromRadians(0)),
	    new Pose2d(1.236, 2.119, Rotation2d.fromRadians(0.502))
	);
	public static final ChoreoTraj NewPath = new ChoreoTraj(
	    "NewPath",
	    OptionalInt.empty(),
	    1.93532,
	    new Pose2d(4.45, 0.45, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(9.6, 0.9, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj NewPath_copy1 = new ChoreoTraj(
	    "NewPath_copy1",
	    OptionalInt.empty(),
	    5.3799,
	    new Pose2d(9.6, 0.9, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(3.091, 0.957, Rotation2d.fromRadians(1.129))
	);
	public static final ChoreoTraj CenterLoopInverted = new ChoreoTraj(
	    "CenterLoopInverted",
	    OptionalInt.empty(),
	    6.18278,
	    new Pose2d(4.45, 0.45, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(2.95, 1.05, Rotation2d.fromRadians(1.046))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("CenterGrab", CenterGrab),
		Map.entry("CenterLoopClose", CenterLoopClose),
		Map.entry("CenterLoopFar", CenterLoopFar),
		Map.entry("CenterScore", CenterScore),
		Map.entry("CloseFuelGrab", CloseFuelGrab),
		Map.entry("CloseFuelScore", CloseFuelScore),
		Map.entry("mirrored_CenterGrab", mirrored_CenterGrab),
		Map.entry("mirrored_CenterLoopClose", mirrored_CenterLoopClose),
		Map.entry("mirrored_CenterLoopFar", mirrored_CenterLoopFar),
		Map.entry("mirrored_CenterScore", mirrored_CenterScore),
		Map.entry("SubstationGrab", SubstationGrab),
		Map.entry("SubstationScore", SubstationScore),
		Map.entry("NewPath", NewPath),
		Map.entry("NewPath_copy1", NewPath_copy1),
		Map.entry("CenterLoopInverted", CenterLoopInverted)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
