
package robot.constants;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj CloseFuelGrab = new ChoreoTraj(
	    "CloseFuelGrab",
	    OptionalInt.empty(),
	    1.29793,
	    new Pose2d(2.5, 6.743, Rotation2d.fromRadians(-0.897)),
	    new Pose2d(0.74, 6.1, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj CloseFuelScore = new ChoreoTraj(
	    "CloseFuelScore",
	    OptionalInt.empty(),
	    0.78065,
	    new Pose2d(0.74, 6.1, Rotation2d.fromRadians(0)),
	    new Pose2d(1.359, 6.443, Rotation2d.fromRadians(-0.616))
	);
	public static final ChoreoTraj SubstationGrab = new ChoreoTraj(
	    "SubstationGrab",
	    OptionalInt.empty(),
	    1.25862,
	    new Pose2d(2.5, 1.3, Rotation2d.fromRadians(0.897)),
	    new Pose2d(0.72, 0.65, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj SubstationScore = new ChoreoTraj(
	    "SubstationScore",
	    OptionalInt.empty(),
	    1.13778,
	    new Pose2d(0.72, 0.65, Rotation2d.fromRadians(0)),
	    new Pose2d(1.236, 2.119, Rotation2d.fromRadians(0.502))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("CloseFuelGrab", CloseFuelGrab),
		Map.entry("CloseFuelScore", CloseFuelScore),
		Map.entry("SubstationGrab", SubstationGrab),
		Map.entry("SubstationScore", SubstationScore)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
