name: Compile and Test Java
run-name: Compile and Test Java
on: [push, pull_request]
jobs:
  Compile-And-Test-Java:
    runs-on: ubuntu-24.04
    container: wpilib/roborio-cross-ubuntu:2025-22.04
    steps:
      - uses: actions/checkout@v6
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Compile and run tests on robot code
        run: ./gradlew build
